POST http://127.0.0.1:9090/categories HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkNhbWlsbyIsImxhc3ROYW1lIjoiQ2hpY28iLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MjQxMTEzNTgxNjgsImlhdCI6MTcyNDEwNTM1OH0.uWlq81gtKA2N2GDhFGPP8RIsasB1ayca5zd9iWcPbRQ

{
    "description": "household appliance"
}

####
GET http://127.0.0.1:9090/categories