version: '3.8'

services:
  postgresdb:
    image: postgres
    env_file:
      - ./.env
    restart: always
    ports:
      - "8001:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAMEDB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}

  app:
    build: .
    depends_on:
      - postgresdb
    env_file:
      - ./.env
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USERNAMEDB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_PORT=${POSTGRES_PORTDB}
